spring:
  application:
    name: library-api-estudo
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update